### ISSUE TITLE
Nice layout! I added polish letters.

### ISSUE THREAD

**Issue by AKmatiAK** [sunaku/engrammer#1]
Hi. Thanks for creating it. What I like in this layout is that I could simply swap keys, install and use it, although I had one problem specific to my keyboard with keys width. If someone from poland want to use it i can share altgr layer.

**Comment by AKmatiAK** [comment]
now I also switched some keys on the right side for better polish. tommorow I will share.

**Comment by AKmatiAK** [comment]
I did further optimizations. I can say it's good enough now to use it.

Polish latin characters arranged all on home row.
![ukladpl](https://user-images.githubusercontent.com/51701971/188674333-485fdffa-4d03-4ba9-be3f-be1c47560ff0.jpg)

**Comment by sunaku** [comment]
Hello, thanks for your feedback.  I think the [Engram discussion forums](https://github.com/binarybottle/engram/discussions) may be a better place for sharing your new layout.  For example, the author developed [a Spanish version of Engram](https://github.com/binarybottle/engram-es) based on community feedback, so I'm confident that Engram's methodology (see Python notebook in Engram's git repo) can be applied to your ideas to develop a Polish version too.  Cheers.
