### ISSUE TITLE
Photos are broken in readme.

### ISSUE THREAD

**Issue by davidfufu** [sunaku/engrammer#3]
As title says.

**Comment by sunaku** [comment]
Thanks for the notice. 🙏  It was working fine when I pushed my last commit 3 months ago... 🤔 and this problem hasn't affected [my other repository](https://github.com/sunaku/beakl15p) so I'm not sure what happened. 🤷

I've fixed this now for the screenshots included in this repository [by following this tip](https://github.com/orgs/community/discussions/68547), however the photos I've included from my blog are triggering the following warning in my browser's developer console: `Content-Security-Policy: The page’s settings blocked the loading of a resource at http://sunaku.github.io/moergo-glove80-keyboard-photograph.jpg (“img-src”). [react-dom.production.min.js:45:249](https://github.githubassets.com/assets/node_modules/react-dom/cjs/react-dom.production.min.js)`.  This appears to be a bug on GitHub's side, as [reported by some fellow users here](https://github.com/orgs/community/discussions/67058).

**Comment by sunaku** [comment]
Fixed now by using the same `githubusercontent` workaround for images from my blog (which is also on GitHub, conveniently).
